//! Embeds `recipes/*.toml` into the binary.
//!
//! One file per program, so adding a map is dropping a file rather than editing
//! Rust — `aws.toml` and `kubectl.toml` will each be larger than every current
//! recipe combined, and a single map file would not survive them.
//!
//! Generates a `(filename, contents)` table rather than concatenating the files:
//! a map error has to be able to name the recipe it came from.

use std::{env, fs, path::Path};

fn main() {
    let dir = Path::new("recipes");
    println!("cargo:rerun-if-changed=recipes");

    let mut files: Vec<_> = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("recipes/ must exist and be readable: {e}"))
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|e| e == "toml"))
        .collect();
    // sorted so the generated table — and therefore any error ordering — does
    // not depend on directory iteration order
    files.sort();

    assert!(
        !files.is_empty(),
        "recipes/ contains no .toml files; the binary would ship with no argument maps"
    );

    let mut generated = String::from(
        "/// Every recipe, as (filename, contents). Generated by build.rs.\n\
         pub static RECIPES: &[(&str, &str)] = &[\n",
    );
    for path in &files {
        println!("cargo:rerun-if-changed={}", path.display());
        let name = path
            .file_name()
            .expect("a directory entry has a name")
            .to_string_lossy();
        generated.push_str(&format!(
            "    ({name:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/recipes/{name}\"))),\n"
        ));
    }
    generated.push_str("];\n");

    let out = Path::new(&env::var("OUT_DIR").expect("OUT_DIR is set by cargo")).join("recipes.rs");
    fs::write(&out, generated).unwrap_or_else(|e| panic!("writing {}: {e}", out.display()));
}
